version: '3'

services:
  app:
    build:
      context: .
    working_dir: /app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    networks:
      - tg-bot-network

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - database:/var/lib/postgresql/data
    expose:
    - "${DB_PORT}"
    ports:
      - '${DB_PORT}:5432'
    command: -p ${DB_PORT}
    networks:
      - tg-bot-network

volumes:
  database:
    driver: local

networks:
  tg-bot-network:
    driver: bridge