version: '3'

services:
  app:
    build:
      context: .
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - NODE_ENV=production

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - '5432:${DB_PORT}'

volumes:
  database:
    driver: local